# ****************************
# @Author Sean Zhang
# @Since 2018-01-05
# @Copyright XLB Develop Team
# ****************************
# Business micro services deployment definition

# stack name
# STACK_APP_CUST

version: "3"

# please note that you must replace following environment values for deploying the stack
# 01. WECHATCUSTOMER_SERVICE_IMAGE_TAG

# please note that following environment values own default value, and you also can change the value if required

services:

  # 授权服务
  insuranceMicroWechatCustomer:
    image: harbor.i-nomi.com/com.fintech/micro-service-wechat-customer:${WECHATCUSTOMER_SERVICE_IMAGE_TAG}
    restart: always
    volumes:
      - application-logs:/data/log
      - transaction-logs:/data/transaction-logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fintech_insurance_overlay
    environment:
      - DISCOVERY_SERVICE_REG_URL=http://discovery:1111/eureka/
      - INSURANCE_FINANCE_REDIS_HOST=${INSURANCE_FINANCE_REDIS_HOST:-r-wz9309cefbfd4234.redis.rds.aliyuncs.com}
      - INSURANCE_FINANCE_REDIS_PORT=${INSURANCE_FINANCE_REDIS_PORT:-6379}
      - INSURANCE_FINANCE_REDIS_PASSWORD=${INSURANCE_FINANCE_REDIS_PASSWORD}
      - INSURANCE_FINANCE_DB_HOST=${INSURANCE_FINANCE_DB_HOST:-rm-wz9ke69ou0n75aeqs.mysql.rds.aliyuncs.com}
    expose:
      - 8003
    command: java -Xmx512m -Duser.timezone=GMT+8 -Dspring.profiles.active=product -jar app.jar
    deploy:
      labels:
        app: service-wechat-customer
        env: product
        category: business
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
      placement:
        constraints:
          - node.role == worker
          - node.labels.node_env == product

networks:
  fintech_insurance_overlay:
    external:
      name: fintech_insurance_overlay

volumes:
  application-logs:
    external: true
  transaction-logs:
    external: true