#logging:
  #level: ERROR

security:
  oauth2:
    client:
      access-token-uri: http://authz_server:9093/oauth/token
      user-authorization-uri: http://authz_server:9093/oauth/authorize
    resource:
      user-info-uri: http://authz_server:9093/users/current

eureka:
  client:
    serviceUrl:
      defaultZone: http://${INSURANCE_FINANCE_DISCOVERY_HOST:discovery}:${INSURANCE_FINANCE_DISCOVERY_PORT:1111}/eureka/

logging:
  level:
    root: warn